# -*- coding: utf-8 -*

string = input("Leet speak : ").upper()
leetstring = string

leetstring = leetstring.replace("A","4")
leetstring = leetstring.replace("B","8")
leetstring = leetstring.replace("C","<")
leetstring = leetstring.replace("D","|)")
leetstring = leetstring.replace("E","3")
leetstring = leetstring.replace("F","|=")
leetstring = leetstring.replace("G","[,")
leetstring = leetstring.replace("I","1")
leetstring = leetstring.replace("J","_|")
leetstring = leetstring.replace("K","|<")
leetstring = leetstring.replace("L","|_")
leetstring = leetstring.replace("M","/x\\")
leetstring = leetstring.replace("N","|\\|")
leetstring = leetstring.replace("O","0")
leetstring = leetstring.replace("P","|O")
leetstring = leetstring.replace("Q","(,)")
leetstring = leetstring.replace("S","5")
leetstring = leetstring.replace("T","7")
leetstring = leetstring.replace("U","|_|")
leetstring = leetstring.replace("V","\\/")
leetstring = leetstring.replace("W","\\X/")
leetstring = leetstring.replace("X","%")
leetstring = leetstring.replace("Y","¥")
leetstring = leetstring.replace("Z","7_")

print(leetstring)